- name: variables
  hosts: all
  tasks:
    - set_fact: 
        YVA_PLATFORM_USER: "{{PLATFORM_USER|default('yva')}}"
        YVA_PLATFORM_ROOT: "{{INIT_PLATFORM_ROOT | default('/srv/data') }}"

- name: prepare user
  hosts: all
  become: yes
  tasks:
    - user:
        name: "{{YVA_PLATFORM_USER}}"
        groups: docker
        append: yes    
    - file:
        path: "{{INIT_PLATFORM_ROOT}}"
        state: directory
        owner: "{{YVA_PLATFORM_USER}}"        
        recurse: true

- name: consul install
  hosts: all
  become: yes  
  tasks:  
    - import_tasks: consul.yml

- name: pre-install yva from install url
  hosts: all
  become: yes
  become_user: "{{YVA_PLATFORM_USER}}"
  vars: 
    INIT_PLATFORM_KV_OVERLOAD: 
      kv: 
        INIT_DOCKER_USER: "{{INIT_DOCKER_USER}}"
        INIT_DOCKER_PASS: "{{INIT_DOCKER_PASS}}"
        PLATFORM_UPDATE_URL: "{{INIT_PLATFORM_RELEASE_URL}}"
        PLATFORM_DOCKER_CR: "{{PLATFORM_DOCKER_CR | default('cr1.yva.ai')}}"
  environment:
    INIT_PLATFORM_RELEASE_URL: "{{INIT_PLATFORM_RELEASE_URL}}"
    INIT_PLATFORM_ROOT: "{{YVA_PLATFORM_ROOT}}"
    INIT_PLATFORM_KV_OVERLOAD: "{{INIT_PLATFORM_KV_OVERLOAD | combine(INIT_PLATFORM_KV_OVERLOAD2 | default({})) |to_json}}"
    INIT_PLATFORM_INSTALL_SCENARIO: internal
    PATH: "/usr/local/bin:/usr/bin:/usr/sbin"
  tasks:   
    - script: install.sh --pre-install
      chdir: /home/{{YVA_PLATFORM_USER}}

- name: pre-install yva from install url
  hosts: all
  become: yes
  become_user: "{{YVA_PLATFORM_USER}}"
  environment:
    DEBUG: 1
  tasks:
    - shell: source /home/{{YVA_PLATFORM_USER}}/.bash_profile; cd {{YVA_PLATFORM_ROOT}}; ./install.sh --hostrole "{{YVA_HOSTROLE}}" --force
      chdir: "{{YVA_PLATFORM_ROOT}}"
      when: YVA_HOSTROLE is defined