- name: install common pakgs 
  hosts: all
  become: yes
  tasks:
    - import_tasks: debian.yml
      when: ansible_facts['os_family'] == 'Debian'

    - import_tasks: redhat.yml
      when: ansible_facts['os_family'] == 'RedHat'