- name: test 
  hosts: all
  become: yes
  tasks:
    - debug:
        var: ansible_facts['os_family'] 
    - debug: 
        var: ansible_distribution

- import_playbook: common/main.yml
  when: no_common is not defined or not no_common

- import_playbook: cuda/main.yml
  when: cuda is defined and cuda

- import_playbook: developer/main.yml
  when: developer is defined and developer

- import_playbook: data/main.yml
  when: data is defined and data

- import_playbook: ml/main.yml
  when: ml is defined and ml

