- name: install common pakgs 
  hosts: all
  become: yes
  tasks:
    - package: 
        name: "{{item}}"
        state: latest 
      with_items:
        - jq 
        - bash 
        - wget
        - curl
        - unzip
        - ca-certificates

    - import_tasks: ubuntu.yml
      when: ansible_facts['os_family'] == 'Debian'

    - import_tasks: redhat.yml
      when: ansible_facts['os_family'] == 'RedHat'

    - import_tasks: consul.yml  
    - import_tasks: docker.yml