- name: install common pakgs 
  hosts: all
  become: yes
  tasks:
    - import_tasks: consul.yml  

    - import_tasks: nvidia.docker.debian.yml
      when: ansible_facts['os_family'] == 'Debian' and cuda is defined and cuda

    - lineinfile: dest=/etc/ssh/sshd_config regexp='^#?AcceptEnv ' line="AcceptEnv INIT_* PLATFORM_* YVA_* FINDO_*"
      notify: restart_sshd
  handlers:
    - name: restart_sshd
      service: 
        name: sshd
        state: restarted 
    - name: restart_docker
      service: 
        name: docker
        state: restarted   